version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  gateway:
    image: siberianfalcon/kittygram_nginx
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/backend_static
      - static:/static
      - media:/media
  backend:
    image: siberianfalcon/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - static:/static
      - media:/media
    depends_on:
      - gateway
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    depends_on:
      - gateway
      - backend
  frontend:
    env_file: .env
    image: siberianfalcon/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/static
